### ISSUE TITLE
New external sources

### ISSUE THREAD

**Issue by realgooseman** [safing/intel-data#74]
Hi Safing team,

A month or so ago, I [posted an issue](https://github.com/safing/portmaster/issues/1551) on the main Portmaster GitHub repo about the need of a custom filter URL option. The answer was that it was requested a lot but not considered for now as you guys are more focused on quality over quantity. I still think giving the option to the end user to choose preset filters or import his own would be better for the overall experience and customization, even if there's a slight privacy risk as Portmaster fetches those custom URL's and possibly send PII data.

It would be great to give that option if the user choses the "Advanced Interface" in UI Mode. Add a privacy risk warning or something to inform and dissociate from risks taken with custom URL's.

In the meantime, here are the three filters I would like seen added in the **sources.yml** for Portmaster.
They're actively maintained, regularly updated and balanced (set & forget):

**[Hagezi - Multi Pro](https://github.com/hagezi/dns-blocklists?tab=readme-ov-file#ledger-multi-pro---extended-protection-recommended-)**
**[Badmojr - 1Hosts Lite](https://github.com/badmojr/1Hosts?tab=readme-ov-file#1hosts-lite)**
**[Firebog - EasyPrivacy](https://v.firebog.net/hosts/Easyprivacy.txt)**

**Comment by Raphty** [comment]
Thanks for the suggestion, I guess you misunderstood, multiple times is absolutely not a lot 😅 

If it were, it would be a higher priority, we see that some people are, for some reason fans of certain filter lists. As funny as this sounds to me 😂 

We might add those lists, I even have been in touch with hagezi in the past clarifying if he would be ok with us using it.

The issue even with "well maintained" lists still is the same - it is a wack a mole game that never ends - Profiles are a great solution.

Adressierung some other smaller things, "possibly send PII" you will always send your IP address if you are not using SPN - that is how the internet works
Also filter lists that are not delubricated and combined take up a lot more space and processor resources - there is a reason PiHole bakes the lists after a pull.

we would have to build something like this - which costs resources we see better spent somewhere else.

If a FOSS contribution for this feature comes around we are happy to engage, to that developer, please reach out in advance and lets talk though the specification first.

I am not saying we will never do this, but since the need seems low, with people asking 3-4 times a year... we will put resources more towards needs people currently have.

**Comment by realgooseman** [comment]
Hi @Raphty,

After rechecking the answer on the original issue, you did indeed say "multiple times"...I guess I exaggerated with "a lot' 😊.
Anyways, glad the implementation is not completely unconsidered. And yes it makes sense to focus on the popular requests and issues first.

Ultimately, Portmaster remains a very useful privacy suite and kinda essential for Windows users at this point. Great job.
